# Generated by Django 4.1.6 on 2023-02-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_desc', models.CharField(max_length=200)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_ingredients', models.CharField(max_length=200)),
                ('recipe_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('biography', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_desc', models.CharField(max_length=200)),
                ('review_rating', models.IntegerField()),
                ('review_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_desc', models.CharField(max_length=200)),
                ('post_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='homeCooked.user')),
                ('post_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='homeCooked.user')),
                ('post_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.review')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('message_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='homeCooked.user')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='homeCooked.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('event_desc', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_capacity', models.IntegerField()),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_desc', models.CharField(max_length=200)),
                ('discussion_data', models.DateField()),
                ('discussion_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.event')),
                ('discussion_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user')),
            ],
        ),
    ]
