# Generated by Django 4.1.7 on 2023-03-01 16:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('health_labels', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_created', models.DateTimeField(auto_created=True, verbose_name='Created Date/Time')),
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Post ID')),
                ('post_title', models.CharField(max_length=100, verbose_name='Title')),
                ('post_desc', models.CharField(max_length=200, verbose_name='Description')),
                ('post_completed', models.DateTimeField(auto_now=True, verbose_name='Completed Date/Time')),
                ('post_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['post_id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Recipe ID')),
                ('recipe_desc', models.CharField(max_length=200, verbose_name='Description')),
                ('recipe_name', models.CharField(max_length=200, verbose_name='Name')),
                ('recipe_ingredients', models.CharField(max_length=200, verbose_name='Ingredients')),
                ('recipe_img', models.CharField(max_length=200, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('user_fid', models.CharField(max_length=200, verbose_name='Firebase ID')),
                ('user_uname', models.CharField(max_length=200, verbose_name='Username')),
                ('user_address', models.CharField(default='', max_length=200, verbose_name='Address')),
                ('user_city', models.CharField(default='', max_length=200, verbose_name='City')),
                ('user_state', models.CharField(default='', max_length=200, verbose_name='State')),
                ('user_bio', models.CharField(default='', max_length=200, verbose_name='Biography')),
                ('image_text', models.CharField(default='', max_length=200, verbose_name='Image text')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Review ID')),
                ('review_desc', models.CharField(max_length=200, verbose_name='Description')),
                ('review_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('review_giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserGiver', to='homeCooked.user')),
                ('review_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.post', verbose_name='Post')),
                ('review_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserReceiver', to='homeCooked.user')),
                ('review_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_consumer',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='homeCooked.user', verbose_name='Consumer'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='homeCooked.user', verbose_name='Producer'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe', verbose_name='Recipe'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('message', models.CharField(max_length=200, verbose_name='Content')),
                ('message_sent', models.DateTimeField(default=datetime.datetime.now, verbose_name='Sent Date/Time')),
                ('message_recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='homeCooked.user', verbose_name='Recipient')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='homeCooked.user', verbose_name='Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Name')),
                ('event_desc', models.CharField(max_length=200, verbose_name='Description')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_time', models.TimeField(verbose_name='Time')),
                ('event_location', models.CharField(max_length=200, verbose_name='Location')),
                ('event_capacity', models.IntegerField(verbose_name='Capacity')),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='Host')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Discussion ID')),
                ('discussion_desc', models.CharField(max_length=200, verbose_name='Description')),
                ('discussion_data', models.DateField(verbose_name='Date')),
                ('discussion_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.event', verbose_name='Event')),
                ('discussion_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='Sender')),
            ],
        ),
    ]
