# Generated by Django 4.1.7 on 2023-03-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True, 'ordering': ['event_id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['post_id']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': True, 'ordering': ['recipe_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['user_id']},
        ),
    ]
