# Generated by Django 4.1.7 on 2023-03-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0002_alter_event_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'managed': True, 'ordering': ['food_name']},
        ),
        migrations.AlterModelOptions(
            name='discussionboard',
            options={'managed': True, 'ordering': ['discussion_id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['message_id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': True, 'ordering': ['review_id']},
        ),
    ]
