# Generated by Django 4.1.7 on 2023-03-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0003_alter_allergy_options_alter_discussionboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='homeCooked.user', verbose_name='Consumer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='homeCooked.user', verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe', verbose_name='Recipe'),
        ),
    ]
