# Generated by Django 4.1.1 on 2023-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0003_post_post_completed_post_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_completed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
