# Generated by Django 4.1.7 on 2023-03-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0002_alter_post_post_recipe'),
        ('homeCooked', '0004_alter_post_post_consumer_alter_post_post_producer_and_more'),
    ]

    operations = [
    ]
