# Generated by Django 4.1.1 on 2023-02-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0004_alter_post_post_completed_alter_post_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_consumer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='homeCooked.user'),
        ),
    ]
