# Generated by Django 4.1.7 on 2023-02-21 02:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0005_alter_post_post_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='placeholder', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='discussion_data',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='discussion_desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='discussion_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='discussion_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Discussion ID'),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='discussion_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_capacity',
            field=models.IntegerField(verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Event ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=200, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='homeCooked.user', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='homeCooked.user', verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_sent',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Sent Date/Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_completed',
            field=models.DateTimeField(auto_now=True, verbose_name='Completed Date/Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_consumer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='homeCooked.user', verbose_name='Consumer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(auto_created=True, verbose_name='Created Date/Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Post ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='homeCooked.user', verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Recipe ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.CharField(max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.CharField(max_length=200, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_desc',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Review ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCooked.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(max_length=200, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
