# Generated by Django 4.1.1 on 2023-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0007_post_post_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='biography',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_pass',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_username',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_available',
            field=models.BooleanField(default=True),
        ),
    ]
