# Generated by Django 4.1.1 on 2023-02-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0008_rename_address_user_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_username',
            new_name='user_uname',
        ),
    ]
