# Generated by Django 4.1.1 on 2023-02-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0009_rename_user_username_user_user_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_city',
            field=models.CharField(default='nowherevile', max_length=200, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(default='kentucky', max_length=200, verbose_name='State'),
            preserve_default=False,
        ),
    ]
