# Generated by Django 4.1.7 on 2023-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0010_user_user_city_user_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(default='', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.CharField(default='', max_length=200, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_city',
            field=models.CharField(default='', max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.CharField(default='', max_length=200, verbose_name='State'),
        ),
    ]
