# Generated by Django 4.1.7 on 2023-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0011_alter_user_user_address_alter_user_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pass',
        ),
        migrations.AddField(
            model_name='user',
            name='user_fid',
            field=models.CharField(default=1, max_length=200, verbose_name='Firebase ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uname',
            field=models.EmailField(max_length=200, verbose_name='Username'),
        ),
    ]
