# Generated by Django 4.1.7 on 2023-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0012_remove_user_user_email_remove_user_user_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uname',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
