# Generated by Django 4.1.6 on 2023-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0013_alter_user_user_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('health_labels', models.CharField(max_length=200)),
            ],
        ),
    ]
