# Generated by Django 4.1.7 on 2023-02-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0014_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.AddField(
            model_name='review',
            name='review_giver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserGiver', to='homeCooked.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserReceiver', to='homeCooked.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='homeCooked.user', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_consumer',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='homeCooked.user', verbose_name='Consumer'),
        ),
    ]
