# Generated by Django 4.1.1 on 2023-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0015_remove_review_review_user_review_review_giver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_text',
            field=models.CharField(default='', max_length=200, verbose_name='Image text'),
        ),
    ]
