# Generated by Django 4.1.7 on 2023-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0016_user_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_sys_tags',
            field=models.CharField(default='', max_length=200, verbose_name='Allergens'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_tags',
            field=models.CharField(default='', max_length=200, verbose_name='Tags'),
        ),
    ]
