# Generated by Django 4.1.7 on 2023-03-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCooked', '0017_post_post_sys_tags_post_post_user_tags'),
        ('homeCooked', '0017_recipe_recipe_sys_tags_recipe_recipe_tags'),
    ]

    operations = [
    ]
